name: Python CI Workflow

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Марусяк Никита Владимирович"
      GROUP_NUMBER: "M3116"

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Print Information
      run: |
        echo "ФИО: $FULL_NAME"
        echo "Номер группы: ${{ env.GROUP_NUMBER }}"
        echo "Ник на Github: ${{ github.actor }}"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -p "*.py"

    - name: Lint code with flake8
      run: |
        flake8 .
